In [1]:
import numpy as np

In [8]:
W = 0.5
y0 = 1
y1 = 10
n = 5

m = np.arange(1, 2 * n + 2)  # length 11
bands = np.arange(y0 - W / 2, y1 + W, W)
Z_k = (bands[:-1] + bands[1:]) / 2
Z_k_m = np.zeros((Z_k.shape[0], m.shape[0]))
for j in range(Z_k.shape[0]):
    for i in range(m.shape[0]):
        Z_k_m[j, i] = Z_k[j] - W / 2 + (m[i] - 1) * W / (2 * n)

In [9]:
print(bands), print(Z_k), print(Z_k_m)

[ 0.75  1.25  1.75  2.25  2.75  3.25  3.75  4.25  4.75  5.25  5.75  6.25
  6.75  7.25  7.75  8.25  8.75  9.25  9.75 10.25]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]
[[ 0.75  0.8   0.85  0.9   0.95  1.    1.05  1.1   1.15  1.2   1.25]
 [ 1.25  1.3   1.35  1.4   1.45  1.5   1.55  1.6   1.65  1.7   1.75]
 [ 1.75  1.8   1.85  1.9   1.95  2.    2.05  2.1   2.15  2.2   2.25]
 [ 2.25  2.3   2.35  2.4   2.45  2.5   2.55  2.6   2.65  2.7   2.75]
 [ 2.75  2.8   2.85  2.9   2.95  3.    3.05  3.1   3.15  3.2   3.25]
 [ 3.25  3.3   3.35  3.4   3.45  3.5   3.55  3.6   3.65  3.7   3.75]
 [ 3.75  3.8   3.85  3.9   3.95  4.    4.05  4.1   4.15  4.2   4.25]
 [ 4.25  4.3   4.35  4.4   4.45  4.5   4.55  4.6   4.65  4.7   4.75]
 [ 4.75  4.8   4.85  4.9   4.95  5.    5.05  5.1   5.15  5.2   5.25]
 [ 5.25  5.3   5.35  5.4   5.45  5.5   5.55  5.6   5.65  5.7   5.75]
 [ 5.75  5.8   5.85  5.9   5.95  6.    6.05  6.1   6.15  6.2   6.25]
 [ 6.25  6.3   6.35 

(None, None, None)

In [17]:
xmin = 0.1 ; xmax = 5.0
zmin = 0.1 ; zmax = 5.0
x_middle = np.full(Z_k.shape[0], (xmin + xmax) / 2)
z_middle = np.full(Z_k.shape[0], (zmin + zmax) / 2)
points = np.column_stack((x_middle, Z_k, z_middle))
print(points), print(points.shape)

[[ 2.55  1.    2.55]
 [ 2.55  1.5   2.55]
 [ 2.55  2.    2.55]
 [ 2.55  2.5   2.55]
 [ 2.55  3.    2.55]
 [ 2.55  3.5   2.55]
 [ 2.55  4.    2.55]
 [ 2.55  4.5   2.55]
 [ 2.55  5.    2.55]
 [ 2.55  5.5   2.55]
 [ 2.55  6.    2.55]
 [ 2.55  6.5   2.55]
 [ 2.55  7.    2.55]
 [ 2.55  7.5   2.55]
 [ 2.55  8.    2.55]
 [ 2.55  8.5   2.55]
 [ 2.55  9.    2.55]
 [ 2.55  9.5   2.55]
 [ 2.55 10.    2.55]]
(19, 3)


(None, None)